# please create this for each model, currently only testing with v11
names:
  0: person
  1: bicycle
  2: car
  3: motorcycle


max_lr: 0.01
min_lr: 0.0001
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3
scale: 0.5
degrees: 0.0
shear: 0.0
translate: 0.1
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
mosaic: 1.0
mix_up: 0.15
flip_ud: 0.0
flip_lr: 0.5
box: 7.5
cls: 0.5
dfl: 1.0
